[Interface]
Address = 10.66.66.1/24
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o ens3 -j MASQUERADE
ListenPort = 51820
PrivateKey = MGapBd9UaB4HvIf2k16eOc1fbv/5sblQ/C3V7LpQung=

[Peer]
PublicKey = 2r3e9YJhu+2rvqgD2W7umBK4EThkTFNLxwO7zsV/wFY=
AllowedIPs = 10.66.66.2/32
Endpoint = 109.252.133.118:2229

[Peer]
PublicKey = N5tqZgLUMzjx9aG3UzkzQjU64FgXDr3xQZ2FiW3X43M=
AllowedIPs = 10.66.66.3/32

[Peer]
PublicKey = Sxn9s1xQe7vdaB+BS2+yJb4eFA4uCKGKrbnGWM90+jw=
AllowedIPs = 10.66.66.4/32

[Peer]
PublicKey = Yry9noNVA5lnmpTl2Trha4RVsvSx94IaSQ6hSntYUwU=
AllowedIPs = 10.66.66.5/32

[Peer]
PublicKey = TqFE841R3f5yq/qpRtAHmy6buotb5a3HG7A2nFgAlEE=
AllowedIPs = 10.66.66.6/32

[Peer]
PublicKey = EBpov4vZ2Q2uYzbb32Q1sH0tiXV/yR5nZzIi1NYB13I=
AllowedIPs = 10.66.66.7/32
[Peer]
PublicKey = HFXnveJv/N6nnswBkrJoJQid3rSeBjw72m/siYXgG2s=
PresharedKey = 2XOYkTTP5+MHq5xPsmz559x+ZxsCrIHbfw+wBAu5bJ0=
AllowedIPs = 10.66.66.11/32

# Принцесса
[Peer]
PublicKey = wgzq2xJf0QV4szboGyyLMYwjmS4GLvKwDVeEj+EBKyA=
PresharedKey = 9SaAIrdLesfHnoo2jXyiA7KHQHawIzL45S9thMBp3Us=
AllowedIPs = 10.66.66.10/32
